name: TradingView Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes UTC
  workflow_dispatch:        # Manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python tradingview_scraper.py
